---
- name: place consul license
  ansible.builtin.copy:
    content: "{{ consul_license }}"
    dest: "/etc/consul.d/consul.hclic"
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    mode: "0400"
  notify:
    - restart consul
  when:
    - consul_license is defined

- name: "create /etc/consul.d/consul.hcl"
  ansible.builtin.template:
    src: "etc/consul.d/consul.hcl.j2"
    dest: "/etc/consul.d/consul.hcl"
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    mode: "0640"
  notify:
    - restart consul

- name: start consul
  ansible.builtin.service:
    name: consul
    state: started
    enabled: true
