---
- name: preflight
  ansible.builtin.include_tasks:
    file: preflight.yml

- name: install consul
  ansible.builtin.include_tasks:
    file: install.yml

- name: configure consul
  ansible.builtin.include_tasks:
    file: configure.yml

# - name: start consul cluster
#   ansible.builtin.include_tasks:
#     file: start.yml
#   when:
#     - consul_server | bool
