---
# molecule_exceptions:
#   - variation: alpine
#     reason: "Not idempotent"
molecule_scenarios:
  - scenario: "default"
    ansible: ["previous", "current", "next"]
    platforms:
      # - "debian9"
      - "debian10"
      - "debian11"
      - "ubuntu1804"
      - "ubuntu2004"
      - "ubuntu2204"
      - "centos7"
      - "centos-stream8"
      # - "centos-stream9"
      # - "ubi8"
      # - "fedora34"
      - "fedora35"
      - "fedora36"
      - "amazonlinux"
      - "rockylinux8"
      - "almalinux8"
#  - scenario: "alternative"
#    ansible: ["previous", "current", "next"]
#    platforms: ["ubuntu1604", "ubuntu1804", "ubuntu2004", "centos7", "centos8"]
