---
molecule_scenarios:
  - scenario: "default"
    ansible: ["previous", "current"]
    platforms:
      - "debian10"
      - "debian11"
      - "ubuntu1804"
      - "ubuntu2004"
      - "ubuntu2204"
      - "centos7"
      - "centos-stream8"
      - "centos-stream9"
      - "amazonlinux"
      - "rockylinux8"
      - "rockylinux9"
      - "almalinux8"
      - "almalinux9"
  - scenario: "cluster"
    ansible: ["previous", "current"]
    platforms:
      - "debian10"
      - "debian11"
      - "ubuntu1804"
      - "ubuntu2004"
      - "ubuntu2204"
      - "centos7"
      - "centos-stream8"
      - "centos-stream9"
      - "amazonlinux"
      - "rockylinux8"
      - "rockylinux9"
      - "almalinux8"
      - "almalinux9"
