---
- name: Converge
  hosts: all
  become: true
  gather_facts: true
  vars:
    consul_config_sections:
      - name: base
        config: |
          datacenter     = "dc1"
          data_dir       = "{{ consul_data_path }}"
          name           = "{{ inventory_hostname }}"
          client_addr    = "{{ consul_bind_addr }}"
          bind_addr      = "{{ consul_bind_addr }}"
          advertise_addr = "{{ consul_bind_addr }}"
      - name: UI
        config: |
          ui_config{
            enabled = true
            metrics_provider = prometheus

          }
      - name: server
        config: |
          server = {{ consul_server }}
          #bootstrap_expect=3
          #encrypt = ""
          #retry_join = ["consul.domain.internal", "10.0.4.67"]
          # or for example
          #retry_join = [{% for server in groups['consul_group'] -%}
          #  "{{ hostvars[server]['inventory_hostname'] }}"{{ ", " if not loop.last else "" }}
          #{%- endfor -%} ]
      - name: logging
        config: |
          log_level            = "INFO"
          log_json             = false
          log_file             = "{{ consul_log_path }}/consul.log"
          log_rotate_duration  = "24h" # rotate after 24h
          log_rotate_max_files = "7"   # keep 1 week worth of logs
      - name: telementry
        config: |
          telemetry {
            prometheus_retention_time  = 60s
          }


  roles:
    - role: "ansible-role-consul"
